from enum import StrEnum


class InvestiveObjectiveEnum(StrEnum):
    TRADING = "Trading"
    GROWTH = "Growth"
    SPECULATION = "Speculation"
    HEDGING = "Hedging"
    PRESERVATION = "Preservation"
    INCOME = "Income"


class BrokerageServiceCodeEnum(StrEnum):
    IBCLEARING = "IBClearing"
    IBEXECUTION = "IBExecution"
    IBPRIME = "IBPrime"


class CapabilityEnum(StrEnum):
    BOND = "BOND"
    FOP = "FOP"
    FUND = "FUND"
    FUT = "FUT"
    MRGN = "MRGN"
    MULT = "MULT"
    OPT = "OPT"
    SSF = "SSF"
    CFD = "CFD"
    STK = "STK"
    CLP = "CLP"
    LEVFX = "LEVFX"
    CMDTY = "CMDTY"


class BaseCurrencyEnum(StrEnum):
    USD = "USD"
    EUR = "EUR"
    GBP = "GBP"
    CAD = "CAD"
    JPY = "JPY"
    HKD = "HKD"
    AUD = "AUD"
    CHF = "CHF"
    MXN = "MXN"
    SEK = "SEK"
    NZD = "NZD"
    HUF = "HUF"
    CZK = "CZK"
    CNH = "CNH"
    DKK = "DKK"
    RUB = "RUB"
    ILS = "ILS"
    NOK = "NOK"
    SGD = "SGD"
    PLN = "PLN"
    ZAR = "ZAR"
    AED = "AED"
    KRW = "KRW"
    SAR = "SAR"
    TRY = "TRY"
    RON = "RON"
    BGN = "BGN"


class IRATypeEnum(StrEnum):
    RI = "RI"
    RO = "RO"
    RT = "RT"
    SP = "SP"
    ED = "ED"
    TH = "TH"
    RH = "RH"
    SH = "SH"
    RRSP = "RRSP"
    SRRSP = "SRRSP"
    TFSA = "TFSA"
    SIMPLE = "SIMPLE"
    ISA = "ISA"
    JISA = "JISA"


class AccountTypeEnum(StrEnum):
    INVESTMENT = "Investment"
    TRADING = "Trading"
    SMSF = "SMSF"


class QISubTypeEnum(StrEnum):
    ISA = "ISA"
    JISA = "JISA"
    SIPP = "SIPP"


class AssetClassEnum(StrEnum):
    BILL = "BILL"
    BOND = "BOND"
    CASH = "CASH"
    CFD = "CFD"
    COMB = "COMB"
    FOP = "FOP"
    FUND = "FUND"
    FUT = "FUT"
    OPT = "OPT"
    SSF = "SSF"
    STK = "STK"
    WAR = "WAR"
    MRGN = "MRGN"
    CLP = "CLP"


class CountryEnum(StrEnum):
    ALL = "ALL"
    AUSTRALIA = "AUSTRALIA"
    AUSTRIA = "AUSTRIA"
    BELGIUM = "BELGIUM"
    CANADA = "CANADA"
    FRANCE = "FRANCE"
    GERMANY = "GERMANY"
    HONG_KONG = "HONG KONG"
    ITALY = "ITALY"
    JAPAN = "JAPAN"
    KOREA = "KOREA"
    MEXICO = "MEXICO"
    NORWAY = "NORWAY"
    SINGAPORE = "SINGAPORE"
    SPAIN = "SPAIN"
    SWEDEN = "SWEDEN"
    SWITZERLAND = "SWITZERLAND"
    THE_NETHERLANDS = "THE NETHERLANDS"
    UNITED_KINGDOM = "UNITED KINGDOM"
    UNITED_STATES = "UNITED STATES"
    HK_CHINA = "HK-CHINA"


class ProductTypeEnum(StrEnum):
    BONDS = "BONDS"
    FUTURES = "FUTURES"
    FOREX = "FOREX"
    FUTURES_OPTIONS = "FUTURES OPTIONS"
    MUTUAL_FUNDS = "MUTUAL FUNDS"
    STOCKS = "STOCKS"
    SINGLE_STOCK_FUTURES = "SINGLE STOCK FUTURES"
    OPTIONS = "OPTIONS"
    STOCK_OPTIONS = "STOCK OPTIONS"
    WARRANTS = "WARRANTS"


class ExchangeEnum(StrEnum):
    NYSE = "NYSE"
    AMEX = "AMEX"
    NASDAQ = "NASDAQ"
    CBOE = "CBOE"
    ISE = "ISE"
    BOX = "BOX"
    PHLX = "PHLX"
    PSE = "PSE"


class SalutationEnum(StrEnum):
    MR = "Mr."
    MRS = "Mrs."
    MS = "Ms."
    DR = "Dr."
    MX = "Mx."
    IND = "Ind."


class NameSuffixEnum(StrEnum):
    JR = "Jr."
    SR = "Sr."
    I = "I"  # noqa: E741
    II = "II"
    III = "III"
    IV = "IV"
    V = "V"


class GenderEnum(StrEnum):
    MALE = "M"
    FEMALE = "F"


class MaritalStatusEnum(StrEnum):
    SINGLE = "S"
    MARRIED = "M"
    WIDOWED = "W"
    DIVORCED = "D"
    CIVIL_PARTNERSHIP = "C"


class PhoneTypeEnum(StrEnum):
    WORK = "Work"
    HOME = "Home"
    FAX = "Fax"
    MOBILE = "Mobile"
    MOBILE_WORK = "Mobile (work)"
    MOBILE_OTHER = "Mobile (other)"
    BUSINESS = "Business"
    OTHER_VOICE = "Other (voice)"


class TINTypeEnum(StrEnum):
    SSN = "SSN"
    EIN = "EIN"
    NON_US_NATIONAL_ID = "NonUS_NationalId"


class FormationTypeEnum(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    OTHER = "OTHER"


class CardColorEnum(StrEnum):
    BLUE = "BLUE"
    GREEN = "GREEN"
    YELLOW = "YELLOW"


class SignatureTypeEnum(StrEnum):
    ELECTRONIC = "Electronic"
    PHYSICAL = "Physical"


class W9CustomerTypeEnum(StrEnum):
    INDIVIDUAL = "Individual"
    CORPORATION = "Corporation"
    PARTNERSHIP = "Partnership"
    LLC = "LLC"
    OTHER = "Other"


class TaxAuthorityEnum(StrEnum):
    ISRAEL = "ISRAEL_TA"
    CANADA = "CANADA_TA"
    RUSSIA = "RUSSIA_TA"
    SWEDEN = "SWEDEN_TA"
    AUSTRALIA = "AUSTRALIA_TA"


class ExplanationTypeEnum(StrEnum):
    US_TIN = "US_TIN"
    TIN_NOT_DISCLOSED = "TIN_NOT_DISCLOSED"
    TIN_NOT_REQUIRED = "TIN_NOT_REQUIRED"
    TIN_NOT_ISSUED = "TIN_NOT_ISSUED"


class ControllingPersonDesignationEnum(StrEnum):
    SENIOR_MGMT_OFFICER = "SENIOR_MGMT_OFFICER"
    BY_OWNERSHIP = "BY_OWNERSHIP"
    BY_OTHER_MEANS = "BY_OTHER_MEANS"


class OECDStatusEnum(StrEnum):
    DEPOSITORY_INSTITUTION = "DEPOSITORY_INSTITUTION"
    CUSTODIAL_INSTITUTION = "CUSTODIAL_INSTITUTION"
    SPECIFIED_INSURANCE_COMPANY = "SPECIFIED_INSURANCE_COMPANY"
    INVESTMENT_ENTITY_IN_NONPARTICIPATING_JURISDICTION = (
        "INVESTMENT_ENTITY_IN_NONPARTICIPATING_JURISDICTION"
    )
    INVESTMENT_ENTITY_NOT_LISTED = "INVESTMENT_ENTITY_NOT_LISTED"
    PUBLICLY_TRADED_CORPORATION_OR_AFFILIATE = (
        "PUBLICLY_TRADED_CORPORATION_OR_AFFILIATE"
    )
    OTHER_ACTIVE_NON_FINANCIAL_ENTITY = "OTHER_ACTIVE_NON_FINANCIAL_ENTITY"
    PASSIVE_NON_FINANCIAL_ENTITY = "PASSIVE_NON_FINANCIAL_ENTITY"
    EXEMPT_RETIREMENT_PLAN = "EXEMPT_RETIREMENT_PLAN"
    NON_REPORTING_FI = "NON_REPORTING_FI"
    OTHER_INVESTMENT_ENTITY = "OTHER_INVESTMENT_ENTITY"
    FINANCIAL_INSTITUTION = "FINANCIAL_INSTITUTION"
    NON_REPORTING_FINANCIAL_INSTITUTION = "NON_REPORTING_FINANCIAL_INSTITUTION"


class ProhibitedQuestionnaireDetailCodeEnum(StrEnum):
    PASSPORT = "PASSPORT"
    CITIZENSHIP = "CITIZENSHIP"
    BUSINESSDEALINGS = "BUSINESSDEALINGS"
    FINANCIALACCOUNTS = "FINANCIALACCOUNTS"
    RESIDENT = "RESIDENT"
    MULTI = "MULTI"
    BIRTH = "BIRTH"


class RelationshipEnum(StrEnum):
    BROTHER = "Brother"
    DAUGHTER = "Daughter"
    ESTATE = "Estate"
    FATHER = "Father"
    HUSBAND = "Husband"
    MOTHER = "Mother"
    OTHER = "Other"
    SISTER = "Sister"
    SON = "Son"
    WIFE = "Wife"
    CHARITY = "Charity"
    TRUST = "Trust"
    SPOUSE = "Spouse"
    CHILD = "Child"
    SIBLING = "Sibling"
    PARENT = "Parent"
    GRANDCHILD = "Grandchild"
    COMMON_LAW_PARTNER = "Common Law Partner"


class TitleCodeEnum(StrEnum):
    ACCOUNT_HOLDER = "Account Holder"
    FIRST_HOLDER = "FIRST HOLDER"
    SECOND_HOLDER = "SECOND HOLDER"
    TRADER = "TRADER"
    CEO = "CEO"
    SECRETARY = "SECRETARY"
    TREASURER = "TREASURER"
    OWNER = "OWNER"
    PRINCIPAL = "PRINCIPAL"
    SHAREHOLDER = "SHAREHOLDER"
    TRUSTEE = "TRUSTEE"
    BENEFICIARY = "BENEFICIARY"
    GRANTOR = "GRANTOR"
    EMPLOYEE = "Employee"
    CONTINGENT = "CONTINGENT"
    IRA_BENEFICIARY = "IRA_BENEFICIARY"
    IRA_DECEDED = "IRA DECEDENT"
    COMP_OFFICER = "COMP_OFFICER"
    OTHER_OFFICER = "Other Officer"
    CONTROLLING_OFFICER = "Controlling Officer"
    SIGNATORY = "SIGNATORY"
    NON_EMPLOYEE = "NON-EMPLOYEE"
    CUSTODIAN = "CUSTODIAN"
    SUCCESSOR_CUSTODIAN = "SUCCESSOR_CUSTODIAN"
    DIRECTOR = "DIRECTOR"
    PARTNER = "PARTNER"
    CUSTODIAN_EMPLOYEE = "CUSTODIAN EMPLOYEE"
    SUCCESSOR_CUSTODIAN_EMPLOYEE = "SUCCESSOR CUSTODIAN EMPLOYEE"
    SPOUSE = "SPOUSE"
    SUCCESSOR_HOLDER = "Successor Holder"
    REGISTERED_CONTACT = "Registered Contact"


class FeeDetailsTypeEnum(StrEnum):
    ANNUALFLATFEE = "ANNUALFLATFEE"
    ANNUALFLATFEE_MONTHLY = "ANNUALFLATFEE_MONTHLY"
    ANNUALFLATFEE_QUATERLY = "ANNUALFLATFEE_QUATERLY"
    PERCENTOFEQUITY = "PERCENTOFEQUITY"
    PERCENTOFEQUITY_MONTHLY = "PERCENTOFEQUITY_MONTHLY"
    PERCENTOFEQUITY_EOM = "PERCENTOFEQUITY_EOM"
    PERCENTOFEQUITY_QUATERLY = "PERCENTOFEQUITY_QUATERLY"
    PERCENTOFEQUITY_QUARTERLY = "PERCENTOFEQUITY_QUARTERLY"
    PERCENTOFEQUITY_EOQ = "PERCENTOFEQUITY_EOQ"
    BLENDEDPERCENTOFEQUITY = "BLENDEDPERCENTOFEQUITY"
    BLENDEDPERCENTOFEQUITY_MONTHLY = "BLENDEDPERCENTOFEQUITY_MONTHLY"
    BLENDEDPERCENTOFEQUITY_EOM = "BLENDEDPERCENTOFEQUITY_EOM"
    BLENDEDPERCENTOFEQUITY_QUARTERLY = "BLENDEDPERCENTOFEQUITY_QUARTERLY"
    BLENDEDPERCENTOFEQUITY_EOQ = "BLENDEDPERCENTOFEQUITY_EOQ"
    INVOICE_LIMIT = "INVOICE_LIMIT"
    INVOICE_LIMIT_Q = "INVOICE_LIMIT_Q"
    PERCENTOFPROFIT = "PERCENTOFPROFIT"
    PERCENTOFPROFIT_QUARTER = "PERCENTOFPROFIT_QUARTER"
    PERTRADE = "PERTRADE"
    PERCENTOFNLV_CAP = "PERCENTOFNLV_CAP"
    PERCENTOFNLV_CAP_EOPEQTY = "PERCENTOFNLV_CAP_EOPEQTY"
    PERCENTOFNLV_CAP_Q = "PERCENTOFNLV_CAP_Q"
    PERCENTOFNLV_CAP_EOPEQTY_Q = "PERCENTOFNLV_CAP_EOPEQTY_Q"


class EntityTypeEnum(StrEnum):
    TRUST = "Trust"
    ESTATE = "Estate"
    CHARITY = "Charity"


class DepositNotificationTypeEnum(StrEnum):
    CHECK = "CHECK"
    WIRE = "WIRE"
    ACH = "ACH"
    SKIP_DEPOSIT = "SKIP_DEPOSIT"


class LanguageEnum(StrEnum):
    EN = "en"
    ZH_HANS = "zh-Hans"
    JA = "ja"
    RU = "ru"
    FR = "fr"
    PT = "pt"
    ES = "es"
    IT = "it"
    AR_AE = "ar-AE"
    DE = "de"
    HE_IL = "he-IL"
    HU = "hu"


class FATCACompliantTypeEnum(StrEnum):
    FATCA_COMPLIANT = "FATCA_COMPLIANT"
    NON_CONSENTING_US_ACCOUNT = "NON_CONSENTING_US_ACCOUNT"
    NON_COOPERATIVE_ACCOUNT = "NON_COOPERATIVE_ACCOUNT"


class FATCAStatusEnum(StrEnum):
    NONPARTICIPATING_FFI = "NONPARTICIPATING_FFI"
    PARICIPATING_FFI = "PARICIPATING_FFI"
    REPORTING_MODEL_1_FFI = "REPORTING_MODEL_1_FFI"
    REPORTING_MODEL_2_FFI = "REPORTING_MODEL_2_FFI"
    REGISTERED_DEEMED_COMPLIANT_FFI = "REGISTERED_DEEMED_COMPLIANT_FFI"
    SPONSORED_FFI = "SPONSORED_FFI"
    CERTIFIED_DEEMED_COMPLIANT_NONREGISTERING_LOCAL_BANK = (
        "CERTIFIED_DEEMED_COMPLIANT_NONREGISTERING_LOCAL_BANK"
    )
    CERTIFIED_DEEMED_COMPLIANT_FFI = "CERTIFIED_DEEMED_COMPLIANT_FFI"
    CERTIFIED_DEEMED_COMPLIANT_SPONSORED_VEHICLE = (
        "CERTIFIED_DEEMED_COMPLIANT_SPONSORED_VEHICLE"
    )
    CERTIFIED_DEEMED_COMPLIANT_LIMITED_LIFE_DEBT = (
        "CERTIFIED_DEEMED_COMPLIANT_LIMITED_LIFE_DEBT"
    )
    CERTIFIED_DEEMED_COMPLIANT_INVESTMENT_ADVISORS = (
        "CERTIFIED_DEEMED_COMPLIANT_INVESTMENT_ADVISORS"
    )
    OWNER_DOCUMENTED_FFI = "OWNER_DOCUMENTED_FFI"
    RESTRICTED_DISTRIBUTOR = "RESTRICTED_DISTRIBUTOR"
    NONREPORTING_IGA_FFI = "NONREPORTING_IGA_FFI"
    FOREIGN_GOVERNMENT = "FOREIGN_GOVERNMENT"
    INTERNATIONAL_ORGANIZATION = "INTERNATIONAL_ORGANIZATION"
    EXEMPT_RETIREMENT_PLANS = "EXEMPT_RETIREMENT_PLANS"
    ENTITY_OWNED_BY_EXEMPT_BENEFICIAL_OWNERS = (
        "ENTITY_OWNED_BY_EXEMPT_BENEFICIAL_OWNERS"
    )
    TERRITORY_FINANCIAL_INSTITUTION = "TERRITORY_FINANCIAL_INSTITUTION"
    NONFINANCIAL_GROUP = "NONFINANCIAL_GROUP"
    EXCEPTED_NONFINANCIAL_STARTUP = "EXCEPTED_NONFINANCIAL_STARTUP"
    EXCEPTED_NONFINANCIAL_ENTITY = "EXCEPTED_NONFINANCIAL_ENTITY"
    AN_501_C_ORGANIZATION = "AN_501_C_ORGANIZATION"
    NONPROFIT_ORGANIZATION = "NONPROFIT_ORGANIZATION"
    PUBLICLY_TRADED_NFFE = "PUBLICLY_TRADED_NFFE"
    EXCEPTED_TERRITORY_NFFE = "EXCEPTED_TERRITORY_NFFE"
    ACTIVE_NFFE = "ACTIVE_NFFE"
    PASSIVE_NFFE = "PASSIVE_NFFE"
    EXCEPTED_INTER_AFFILIATE_FFI = "EXCEPTED_INTER_AFFILIATE_FFI"
    DIRECT_REPORTING_NFFE = "DIRECT_REPORTING_NFFE"
    SPONSORED_DIRECT_REPORTING_NFFE = "SPONSORED_DIRECT_REPORTING_NFFE"


class OwnerTypeEnum(StrEnum):
    INDIVIDUAL = "INDIVIDUAL"
    LEGAL_ENTITY = "LEGAL_ENTITY"
    TRUST = "TRUST"


class RegulatoryDetailCodeEnum(StrEnum):
    CRIMINAL = "CRIMINAL"
    AFFILIATION = "AFFILIATION"
    CFTCREGISTERED = "CFTCREGISTERED"
    IBACCOUNTS = "IBACCOUNTS"
    REGULATORYCONTROL = "REGULATORYCONTROL"
    EMPLOYEE_PUB_TRADE = "EmployeePubTrade"
    CONTROL_PUB_TRADED = "ControlPubTraded"
    BROKER_DEALER = "BROKERDEALER"
    EXCHANGE_MEMBERSHIP = "EXCHANGEMEMBERSHIP"
    STOCK_CONTROL = "STOCKCONTROL"
    DISPUTE = "DISPUTE"
    INVESTIGATION = "INVESTIGATION"
    MEMBERSHIP = "MEMBERSHIP"
    AUSEXPOSURE = "AUSEXPOSURE"
    CONTROLLER = "CONTROLLER"
    POLITICAL_MILITARY_DIPLOMATIC = "POLITICALMILITARYDIPLOMATIC"
    FOREIGN_BANK = "FOREIGN_BANK"
    BROKER_DEALER = "BROKER_DEALER"
    FUTURES_COMMISSION_MERCHANT = "FUTURES_COMMISSION_MERCHANT"
    MUTUAL_FUND = "MUTUAL_FUND"
    FOREIGN_EXCHANGE = "FOREIGN_EXCHANGE"
    MONEY_TRANSMITTER = "MONEY_TRANSMITTER"
    EMPLOYEE_BENEFIT_PLAN = "EMPLOYEE_BENEFIT_PLAN"
    US_BANK = "US_BANK"
    US_SWAP_DEALER = "US_SWAP_DEALER"
    US_SWAP_PARTICIPANT = "US_SWAP_PARTICIPANT"
    US_INSURANCE_COMPANY = "US_INSURANCE_COMPANY"
    NON_US_INSURANCE_COMPANY = "NON_US_INSURANCE_COMPANY"
    US_DEPT = "US_DEPT"
    FINANCIAL_ADVISOR = "FINANCIAL_ADVISOR"
    HIGH_RISK_CONTRIBUTION = "HIGH_RISK_CONTRIBUTION"


class SourceOfIncomeTypeEnum(StrEnum):
    CONSULTING = "CONSULTING"
    DISABILITY = "DISABILITY"
    INHERITANCE = "INHERITANCE"
    INTEREST = "INTEREST"
    REALESTATE = "REALESTATE"
    RENTAL = "RENTAL"
    SEVERANCE = "SEVERANCE"
    SPOUSE = "SPOUSE"
    TRADING_AND_INVESTMENTS = "TRADINGANDINVESTMENTS"
    PENSION_AND_SOCIAL_SECURITY = "PENSIONANDSOCIALSECURITY"
    UNEMPLOYMENT = "UNEMPLOYMENT"
    OTHER = "OTHER"


class SourceOfWealthTypeEnum(StrEnum):
    SOW_IND_ALLOWANCE = "SOW-IND-Allowance"
    SOW_IND_DISABILITY = "SOW-IND-Disability"
    SOW_IND_INCOME = "SOW-IND-Income"
    SOW_IND_INHERITANCE = "SOW-IND-Inheritance"
    SOW_IND_INTEREST = "SOW-IND-Interest"
    SOW_IND_MARKET_PROFIT = "SOW-IND-MarketProfit"
    SOW_IND_OTHER = "SOW-IND-Other"
    SOW_IND_PENSION = "SOW-IND-Pension"
    SOW_IND_PROPERTY = "SOW-IND-Property"
    SOW_ORG_BUSINESS = "SOW-ORG-Business"
    SOW_ORG_MARKET_TRADING_PROFITS = "SOW-ORG-MarketTradingProfits"
    SOW_ORG_OTHER = "SOW-ORG-Other"
    SOW_ORG_OWNER_EQUITY = "SOW-ORG-OwnerEquity"
    SOW_ORG_PROPERTY = "SOW-ORG-Property"
    SOW_ORG_RETAINED_EARNINGS = "SOW-ORG-RetainedEarnings"


class KnowledgeLevelEnum(StrEnum):
    EXTENSIVE = "Extensive"
    GOOD = "Good"
    LIMITED = "Limited"
    NONE = "None"


class CustomerTypeEnum(StrEnum):
    INDIVIDUAL = "Individual"
    JOINT = "Joint"
    TRUST = "Trust"
    UGMA = "UGMA"
    UTMA = "UTMA"
    ORG = "Org"
    IRA = "IRA"
